---
version: 0.2.0
config:
  retry_delay_sec: 5.0                  # Optional: Number of seconds to wait before attempting
                                        # to re-establish a broken connection.
targets:
  - name: Hello MiniKube                # Optional, for display purposes.
    tags:                               # Optional, allows to selectively forward using `--tags <tag1> <tag2>`
      - integration
    target: minikune-cluster-2-app-5c59d7b8d4-jg5lh    # The name of the resource to forward to.
    type: pod                           # The type of resource "pod".
    cluster : cluster-3-multinode
    namespace: default                      # The namespace of the resource; defaults to "default".
    listen_addrs:                       # Optional, the listen addresses to use; defaults to "localhost".
      - "127.0.0.1"
    ports:                              # The source ports to forward.
     - "7080:8080"                       # Forward resource port 80 to local port 5012.
  - name: Hola MiniKube                # Optional, for display purposes.
    tags:                               # Optional, allows to selectively forward using `--tags <tag1> <tag2>`
      - integration
    target: minikune-cluster-3-app-c4866c559-gxqmw    # The name of the resource to forward to.
    type: pods                           # The type of resource "pod".
    namespace: default                      # The namespace of the resource; defaults to "default".
    listen_addrs:                       # Optional, the listen addresses to use; defaults to "localhost".
      - "127.0.0.1"
    ports:                              # The source ports to forward.
      - "6080:8080"                       # Forward resource port 80 to local port 5012.
  - name: Hola Hola MiniKube                # Optional, for display purposes.
    tags:                               # Optional, allows to selectively forward using `--tags <tag1> <tag2>`
      - integration
    target: hola-hola-minikube-5fdf74f9c6-x5t8j    # The name of the resource to forward to.
    type: pods                           # The type of resource "pod".
    namespace: default                      # The namespace of the resource; defaults to "default".
    cluster : cluster-2
    listen_addrs:                       # Optional, the listen addresses to use; defaults to "localhost".
      - "127.0.0.1"
    ports:                              # The source ports to forward.
      - "5080:8080"                       # Forward resource port 80 to local port 5012.


# Implement for different cluster & for services as well